apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qgu346upr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qgu346upr-nodejs 
  name: qgu346upr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qgu346upr-nodejs 
