apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qgu346upr-nodejs 
  janus-idp.io/tekton: qgu346upr-nodejs
  backstage.io/kubernetes-id: qgu346upr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qgu346upr-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml